services:
  hrms_backend:
    build:
      context: ./backend-project
      dockerfile: Dockerfile
    container_name: hrms-portal-backend
    command: gunicorn hrms.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8891:8000"
    env_file:
      - ./backend-project/.env
    depends_on:
      - hrms_db
      - hrms_redis
    volumes:
      - static_volume:/staticfiles   
    restart: unless-stopped

  hrms_frontend:
    image: nginx:alpine
    container_name: hrms-portal-frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles
      - media_volume:/media
    ports:
      - "8892:80"
    depends_on:
      - hrms_backend
    restart: unless-stopped

  hrms_db:
    image: mysql:8.0
    container_name: hrms-portal-db
    environment:
      MYSQL_DATABASE: hrms_db
      MYSQL_USER: hrms_user
      MYSQL_PASSWORD: strongpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  hrms_redis:
    image: redis:7
    container_name: hrms-portal-redis
    restart: unless-stopped

volumes:
  mysql_data:
  static_volume:
  media_volume:

